{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nginx.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $dns := .Values.dns -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
{{- range .Values.subdomains }}
      - {{ . }}.{{ $dns }}
{{- end }}
      secretName: letsencrypt
  rules:
{{- range .Values.subdomains }}
    - host: {{ . }}.{{ $dns }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-protected
  labels:
    app: {{ template "nginx.name" . }}-protected
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: htpasswd
spec:
  tls:
    - hosts:
{{- range $domain, $_ := .Values.protectedSubdomains }}
      - {{ $domain }}.{{ $dns }}
{{- end }}
      secretName: letsencrypt
  rules:
{{- range $domain, $path := .Values.protectedSubdomains }}
    - host: {{ $domain }}.{{ $dns }}
      http:
        paths:
          - path: {{ $path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
{{- end }}
