.only-docs:
  only:
    changes:
      - ".gitlab-ci.yml"
      - "docs/**/*"

variables:
  DOCUMENTATION_URL: "https://misakey.pages.misakey.dev/backend/"

build-index:
  image:
    name: node:latest
  extends:
    - .only-master-and-manual
    - .only-docs
  stage: docs
  tags:
    - misakey_docker
  script:
    - npm install grunt string toml
    - npm install -g grunt
    - cd docs && grunt lunr-index
  artifacts:
    name: "docs:index-$CI_PIPELINE_ID"
    paths:
      - docs/static/js/lunr
    expire_in: 1 hour

pages:
  image:
    name: klakegg/hugo:latest
    entrypoint: [""]
  dependencies:
   - build-index
  extends:
    - .only-master-and-manual
    - .only-docs
  stage: build
  tags:
    - misakey_docker
  script:
    - echo "Will deploy documentation on $DOCUMENTATION_URL"
    - hugo -s docs --baseURL "$DOCUMENTATION_URL"
    - cp -r docs/public public
  artifacts:
    paths:
      - public
