.only-api:
  only:
    changes:
      - ".gitlab-ci.yml"
      - "api/**/*"

.except-wip-or-non-api-tags:
  except:
    variables:
      - $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /\+api$/
      - $CI_COMMIT_MESSAGE && $CI_COMMIT_MESSAGE =~ /^wip:/

api:install_mod:
  extends:
    - .only-branches
    - .only-api
    - .except-wip-or-non-api-tags
  stage: dep
  image: golang:1.14
  tags:
    - misakey_go
  script:
    - make -C api dep
  artifacts:
    name: "api:vendor-$CI_PIPELINE_ID"
    paths:
      - api/vendor/
    expire_in: 1 hour

api:lint_code:
  extends:
    - .only-branches
    - .only-api
    - .except-wip-or-non-api-tags
  stage: test
  image: golang:1.14
  dependencies:
    - api:install_mod
  tags:
    - misakey_go
  script:
    - make -C api lint
  needs:
    - api:install_mod

api:unit_tests:
 extends:
   - .only-branches
   - .only-api
   - .except-wip-or-non-api-tags
 stage: test
 image: golang:1.14
 dependencies:
   - api:install_mod
 tags:
   - misakey_go
 script:
   - make -C api test
 needs:
   - api:install_mod

api:build:
  extends:
    - .only-master-and-manual
    - .only-api
    - .except-wip-or-non-api-tags
  stage: build
  image: docker:19.03.8 #Fixme: put back stable when gitlab is updated
  dependencies:
    - api:install_mod
  tags:
    - misakey_docker
  before_script:
    - apk add make
    - apk add git
    - make docker-login
  script:
    - make -C api build
    - make -C api deploy
  needs:
    - api:install_mod
    - api:lint_code
